manifest:
  remotes:
    - name: edtoaster
      url-base: https://github.com/edtoaster
  projects:
    - name: zmk
      remote: edtoaster
      revision: main
      import: app/west.yml
  self:
    path: config
